//
//  ServerListViewViewController.swift
//  Prova_MindMiners
//
//  Created by Eric Winston on 17/05/20.
//  Copyright (c) 2020 Eric Winston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Protocol
protocol ServerListDisplayLogic: class {
    func showServers(viewModel: ServerList.LoadServer.ViewModel)
    func showStatus(viewModel: ServerList.CheckStatus.ViewModel)
}

//MARK: - Class
class ServerListViewController: UIViewController, ServerListDisplayLogic {
    
    //MARK: - Setup
    var interactor: ServerListBusinessLogic?
    
    private func setup() {
        let viewController = self
        let interactor = ServerListInteractor()
        let presenter = ServerListPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    //MARK: - Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: "ServerListViewController", bundle: nibBundleOrNil)
        self.setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setup()
    }
    
    //MARK: - Variables
    @IBOutlet var tableview: UITableView?
    @IBOutlet var navigation: UINavigationBar?
    
    public var servers: [Server] = []
    let refreshControl = UIRefreshControl()
    
    //MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.navigation?.delegate = self
        let navItem = UINavigationItem(title: "Servidores")
        let addItem = UIBarButtonItem(barButtonSystemItem: .add, target: nil, action: #selector(self.addServer))
        addItem.tintColor = .black
        navItem.rightBarButtonItem = addItem
        navigation?.setItems([navItem], animated: false)
        
        self.tableview?.register(UINib(nibName: "ServerListTableViewCell", bundle: nil), forCellReuseIdentifier: "ServerListTableViewCell")
        
        let myTimer = Timer(timeInterval: 15, repeats: true, block: { (timer) in
            self.loadStatus()
        })
        
        RunLoop.main.add(myTimer, forMode: .common)
        
        refreshControl.addTarget(self, action: #selector(self.reloadServers), for: .valueChanged)
        self.tableview?.refreshControl = refreshControl
        
        self.loadServers()
    }
    
    //MARK: - Fetch logic
    func saveServers() {
        let request = ServerList.SaveServer.Request(servers: self.servers)
        self.interactor?.saveServer(request: request)
    }
    
    func loadServers() {
        let request = ServerList.LoadServer.Request()
        self.interactor?.loadServer(request: request)
    }
    
    func loadStatus() {
        let request = ServerList.CheckStatus.Request(servers: self.servers)
        self.interactor?.checkServerStatus(request: request)
    }
    
    //MARK: - Display logic
    func showServers(viewModel: ServerList.LoadServer.ViewModel) {
        self.servers = viewModel.servers ?? []
        self.loadStatus()
        self.tableview?.reloadData()
    }
    
    func showStatus(viewModel: ServerList.CheckStatus.ViewModel) {
        self.servers = viewModel.servers
        self.tableview?.reloadData()
    }
    
    
    @objc func addServer() {
        var newServer = ""
        
        let alertController = UIAlertController(title: "Adicionar Servidor", message: nil, preferredStyle: .alert)
        alertController.addTextField(configurationHandler: nil)
        
        alertController.addAction(UIAlertAction(title: "Cancelar", style: .default, handler: nil))
        alertController.addAction(UIAlertAction(title: "Adicionar", style: .default, handler: { (_) in
            
            newServer = alertController.textFields?[0].text ?? ""
            
            if newServer.count >= 3 {
                self.servers.append(Server(name: newServer, status: ""))
                self.loadStatus()
                self.saveServers()
                self.tableview?.reloadData()
            } else {
                let invalidController = UIAlertController(title: "Nome invalido", message: nil, preferredStyle: .alert)
                invalidController.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
                self.present(invalidController, animated: true, completion: nil)
            }
        }))
        self.present(alertController, animated: true, completion: nil)
    }
    
    @objc func reloadServers(){
        self.tableview?.reloadData()
        self.refreshControl.endRefreshing()
    }
}

//MARK: - Table View Extension
extension ServerListViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return servers.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "ServerListTableViewCell", for: indexPath) as? ServerListTableViewCell else {
            fatalError("Invalid cell dequeue")
        }
        
        cell.serverNameLabel?.text = servers[indexPath.row].name
        cell.serverStatusLabel?.text = servers[indexPath.row].status
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
        let alertController = UIAlertController(title: "Remover Servidor", message: nil, preferredStyle: .alert)
        alertController.addAction(UIAlertAction(title: "Cancelar", style: .default, handler: nil))
        alertController.addAction(UIAlertAction(title: "Remover", style: .default, handler: { (_) in
            
            self.servers.remove(at: indexPath.row)
            self.saveServers()
            self.tableview?.deleteRows(at: [indexPath], with: .automatic)
        }))
        self.present(alertController, animated: true, completion: nil)
        self.tableview?.deselectRow(at: indexPath, animated: false)
    }
}

//MARK: - Navigation Bar Extension
extension ServerListViewController: UINavigationBarDelegate {
    func position(for bar: UIBarPositioning) -> UIBarPosition {
        return UIBarPosition.topAttached
    }
}
