//
//  ServerListViewViewController.swift
//  Prova_MindMiners
//
//  Created by Eric Winston on 17/05/20.
//  Copyright (c) 2020 Eric Winston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ServerListViewDisplayLogic: class {
    func displaySomething(viewModel: ServerListView.Something.ViewModel)
}

class ServerListViewViewController: UIViewController, ServerListViewDisplayLogic {

    // MARK: - Setup

    var interactor: ServerListViewBusinessLogic?

    private func setup() {
        let viewController = self
        let interactor = ServerListViewInteractor()
        let presenter = ServerListViewPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }

    // MARK: - Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        self.setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setup()
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        self.doSomething()
    }

    // MARK: - Variables

    //@IBOutlet weak var nameTextField: UITextField!

    // MARK: - Fetch logic

    func doSomething() {
        let request = ServerListView.Something.Request()
        self.interactor?.doSomething(request: request)
    }

    // MARK: - Display logic

    func displaySomething(viewModel: ServerListView.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }

    // MARK: - IBActionS
}
