//
//  ServerListViewInteractor.swift
//  Prova_MindMiners
//
//  Created by Eric Winston on 17/05/20.
//  Copyright (c) 2020 Eric Winston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: -  Protocol
protocol ServerListBusinessLogic {
    func saveServer(request: ServerList.SaveServer.Request)
    func loadServer(request: ServerList.LoadServer.Request)
}


//MARK: - Class
class ServerListInteractor: ServerListBusinessLogic {
    var presenter: ServerListPresentationLogic?
    var worker: ServerListWorker?
    
    //MARK: - Load Logic
    func saveServer(request: ServerList.SaveServer.Request) {
        worker = ServerListWorker()
        worker?.saveServer(servers: request.servers)
    }
    
    func loadServer(request: ServerList.LoadServer.Request) {
        worker = ServerListWorker()
        worker?.loadServer(completionHandler: { (servers) in
            let response = ServerList.LoadServer.Response(servers: servers)
            self.presenter?.presentServers(response: response)
        })
    }
}
