//
//  ServerListViewPresenter.swift
//  Prova_MindMiners
//
//  Created by Eric Winston on 17/05/20.
//  Copyright (c) 2020 Eric Winston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Protocol
protocol ServerListViewPresentationLogic {
    func presentSomething(response: ServerListView.Something.Response)
}

//MARK: - Class
class ServerListViewPresenter: ServerListViewPresentationLogic {
    weak var viewController: ServerListViewDisplayLogic?
    
    //MARK: - Do something
    
    func presentSomething(response: ServerListView.Something.Response) {
        let viewModel = ServerListView.Something.ViewModel()
        self.viewController?.displaySomething(viewModel: viewModel)
    }
}
