//
//  ServerListViewWorker.swift
//  Prova_MindMiners
//
//  Created by Eric Winston on 17/05/20.
//  Copyright (c) 2020 Eric Winston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Class
class ServerListWorker {
    
    typealias LoadHandler = (([String]?) -> Void)
    
    //MARK: - Work
    func saveServer(servers: [String]) {
        let user = UserDefaults.standard
        user.set(servers, forKey: "Servers")
    }
    
    func loadServer(completionHandler: LoadHandler?) {
        let user = UserDefaults.standard
    
        if let servers = user.array(forKey: "Servers") {
            completionHandler?(servers as? [String])
        }
    }
}
